### ISSUE TITLE
Composer install failed

### ISSUE THREAD

**Issue by plastikschnitzer** [mageplaza/magento-2-ukrainian-language-pack#1]
Hi,
I installed several language packs from mageplaza with composer, but uk_UA fails with the following error message:

`The requested package mageplaza/magento-2-ukrainian-language-pack could not be found in any version, there may be a typo in the package name.`

I have copied the command from your github description:

`composer require mageplaza/magento-2-ukrainian-language-pack:dev-master`

Best regards,
Plastikschnitzer

**Comment by imsamthomas** [comment]
Hi,

Sorry, we missed this message.
We have fixed this issue.
